import type { UMLDiagram } from '../types/uml';
import { generateSpringBootCode } from './codeGenerator';

interface ExportFile {
  path: string;
  content: string;
}

export class ProjectExporter {
  private diagram: UMLDiagram;
  private projectName: string;
  private packageName: string;

  constructor(diagram: UMLDiagram, projectName = 'uml-generated-project', packageName = 'com.example.demo') {
    this.diagram = diagram;
    this.projectName = projectName;
    this.packageName = packageName;
  }

  exportCompleteProject(): ExportFile[] {
    const files: ExportFile[] = [];

    // Generate Spring Boot code
    const generatedCode = generateSpringBootCode(this.diagram, this.packageName);

    // Add generated Java files
    generatedCode.forEach((file) => {
      const packagePath = this.packageName.replace(/\./g, '/');
      let subPath = '';

      switch (file.type) {
        case 'entity':
          subPath = 'entity';
          break;
        case 'repository':
          subPath = 'repository';
          break;
        case 'service':
          subPath = 'service';
          break;
        case 'controller':
          subPath = 'controller';
          break;
        case 'dto':
          subPath = 'dto';
          break;
      }

      files.push({
        path: `src/main/java/${packagePath}/${subPath}/${file.filename}`,
        content: file.content,
      });
    });

    // Add configuration files
    files.push(...this.generateConfigurationFiles());

    // Add main application class
    files.push(this.generateMainApplication());

    // Add build files
    files.push(this.generatePomXml());

    // Add README
    files.push(this.generateReadme());

    // Add Docker files
    files.push(this.generateDockerfile());
    files.push(this.generateDockerCompose());

    return files;
  }

  private generateConfigurationFiles(): ExportFile[] {
    return [
      {
        path: 'src/main/resources/application.yml',
        content: `spring:
  application:
    name: ${this.projectName}
  
  # Database Configuration
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    
  # JPA Configuration  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.SnakeCasePhysicalNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console
      
  # Web Configuration
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Logging Configuration
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    ${this.packageName}: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
`,
      },
      {
        path: 'src/main/resources/data.sql',
        content: `-- Sample data for generated entities
-- This file is executed automatically when the application starts

-- Uncomment and modify the following lines to add initial data:

${this.diagram.entities
  .filter(entity => entity.type === 'class')
  .map(entity => {
    const attributeNames = entity.attributes.map(attr => attr.name.toLowerCase()).join(', ');
    return `-- INSERT INTO ${this.toSnakeCase(entity.name)} (${attributeNames}) VALUES ();`;
  })
  .join('\n')}

-- Example:
-- INSERT INTO users (name, email, created_date) VALUES ('John Doe', 'john@example.com', '2024-01-01');
`,
      },
      {
        path: 'src/main/resources/schema.sql',
        content: `-- Database schema will be auto-generated by Hibernate
-- This file is for custom schema modifications if needed

-- Example custom indexes:
${this.diagram.entities
  .filter(entity => entity.type === 'class')
  .map(entity => {
    const tableName = this.toSnakeCase(entity.name);
    return entity.attributes
      .filter(attr => attr.isKey && attr.name !== 'id')
      .map(attr => `-- CREATE INDEX idx_${tableName}_${this.toSnakeCase(attr.name)} ON ${tableName}(${this.toSnakeCase(attr.name)});`)
      .join('\n');
  })
  .filter(sql => sql.length > 0)
  .join('\n')}
`,
      },
    ];
  }

  private generateMainApplication(): ExportFile {
    const className = this.toPascalCase(this.projectName) + 'Application';

    return {
      path: `src/main/java/${this.packageName.replace(/\./g, '/')}/${className}.java`,
      content: `package ${this.packageName};

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.transaction.annotation.EnableTransactionManagement;
import org.springframework.web.servlet.config.annotation.CorsRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
@EnableTransactionManagement
public class ${className} {

    public static void main(String[] args) {
        SpringApplication.run(${className}.class, args);
    }
    
    @Bean
    public WebMvcConfigurer corsConfigurer() {
        return new WebMvcConfigurer() {
            @Override
            public void addCorsMappings(CorsRegistry registry) {
                registry.addMapping("/api/**")
                        .allowedOrigins("*")
                        .allowedMethods("GET", "POST", "PUT", "DELETE", "OPTIONS")
                        .allowedHeaders("*");
            }
        };
    }
}
`,
    };
  }

  private generatePomXml(): ExportFile {
    return {
      path: 'pom.xml',
      content: `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
         https://maven.apache.org/xsd/maven-4.0.0.xsd">
    
    <modelVersion>4.0.0</modelVersion>
    
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.0</version>
        <relativePath/>
    </parent>
    
    <groupId>${this.packageName}</groupId>
    <artifactId>${this.projectName}</artifactId>
    <version>1.0.0</version>
    <name>${this.toPascalCase(this.projectName)}</name>
    <description>Generated Spring Boot project from UML Class Diagram</description>
    
    <properties>
        <java.version>17</java.version>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
    </properties>
    
    <dependencies>
        <!-- Spring Boot Starters -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        
        <!-- Database -->
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>runtime</scope>
        </dependency>
        
        <!-- Development Tools -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>
        
        <!-- Testing -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        
        <!-- Optional: API Documentation -->
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>2.2.0</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-devtools</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
`,
    };
  }

  private generateDockerfile(): ExportFile {
    return {
      path: 'Dockerfile',
      content: `FROM openjdk:17-jdk-slim

WORKDIR /app

# Copy Maven wrapper and pom.xml
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .

# Download dependencies
RUN ./mvnw dependency:go-offline -B

# Copy source code
COPY src src

# Build application
RUN ./mvnw clean package -DskipTests

# Run application
EXPOSE 8080
CMD ["java", "-jar", "target/${this.projectName}-1.0.0.jar"]
`,
    };
  }

  private generateDockerCompose(): ExportFile {
    return {
      path: 'docker-compose.yml',
      content: `version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  # Uncomment for MySQL database
  # mysql:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_DATABASE: ${this.projectName.replace(/-/g, '_')}
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   restart: unless-stopped

# volumes:
#   mysql_data:
`,
    };
  }

  private generateReadme(): ExportFile {
    const classEntities = this.diagram.entities.filter(entity => entity.type === 'class');
    
    return {
      path: 'README.md',
      content: `# ${this.toPascalCase(this.projectName)}

This Spring Boot project was automatically generated from a UML Class Diagram using the **UML Diagram Tool**.

## 📋 Project Overview

- **Entities**: ${classEntities.length} classes with JPA annotations
- **Repositories**: Spring Data JPA repositories for data access
- **Services**: Business logic layer with CRUD operations and transactions
- **Controllers**: REST API endpoints with error handling
- **DTOs**: Data Transfer Objects for API communication
- **Relations**: ${this.diagram.relations.length} relationships between entities

## 🏗️ Generated Classes

${classEntities
  .map(entity => {
    const attributes = entity.attributes.map(attr => `${attr.name} (${attr.type})`).join(', ');
    const relations = this.diagram.relations.filter(rel => rel.source === entity.id || rel.target === entity.id);
    
    return `### ${entity.name}
**Attributes**: ${attributes || 'None'}
**Relations**: ${relations.length} relationships
**API Endpoints**:
- \`GET /api/${entity.name.toLowerCase()}s\` - Get all ${entity.name}s
- \`GET /api/${entity.name.toLowerCase()}s/{id}\` - Get ${entity.name} by ID
- \`POST /api/${entity.name.toLowerCase()}s\` - Create new ${entity.name}
- \`PUT /api/${entity.name.toLowerCase()}s/{id}\` - Update ${entity.name}
- \`DELETE /api/${entity.name.toLowerCase()}s/{id}\` - Delete ${entity.name}
${entity.attributes.filter(attr => attr.type === 'String').length > 0 ? 
`- \`GET /api/${entity.name.toLowerCase()}s/search?{attribute}={value}\` - Search by attribute` : ''}
`;
  })
  .join('\n')}

## 🚀 Quick Start

### Prerequisites
- **Java 17** or higher
- **Maven 3.6** or higher
- **Git** (optional)

### Running the Application

1. **Clone or extract the project**:
   \`\`\`bash
   cd ${this.projectName}
   \`\`\`

2. **Run with Maven**:
   \`\`\`bash
   ./mvnw spring-boot:run
   \`\`\`

3. **Or build and run the JAR**:
   \`\`\`bash
   ./mvnw clean package
   java -jar target/${this.projectName}-1.0.0.jar
   \`\`\`

### Using Docker

1. **Build and run with Docker**:
   \`\`\`bash
   docker build -t ${this.projectName} .
   docker run -p 8080:8080 ${this.projectName}
   \`\`\`

2. **Or use Docker Compose**:
   \`\`\`bash
   docker-compose up
   \`\`\`

## 🌐 Access Points

Once the application is running:

- **API Base URL**: http://localhost:8080/api
- **H2 Database Console**: http://localhost:8080/h2-console
  - **JDBC URL**: \`jdbc:h2:mem:testdb\`
  - **Username**: \`sa\`
  - **Password**: \`password\`
- **API Documentation** (Swagger): http://localhost:8080/swagger-ui.html

## 📊 Database Schema

The application uses **H2 in-memory database** for development. The schema is automatically generated from your UML entities.

### Generated Tables:
${classEntities
  .map(entity => `- \`${this.toSnakeCase(entity.name)}\` - ${entity.attributes.length} columns`)
  .join('\n')}

## 🔧 Customization

### Database Configuration

To use **MySQL** instead of H2, update \`application.yml\`:

\`\`\`yaml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${this.projectName.replace(/-/g, '_')}
    username: your_username
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
\`\`\`

And add MySQL dependency to \`pom.xml\`:

\`\`\`xml
<dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
    <scope>runtime</scope>
</dependency>
\`\`\`

### Adding Business Logic

1. **Custom Queries**: Add to Repository interfaces
2. **Business Rules**: Implement in Service classes
3. **Validation**: Add annotations to Entity fields
4. **Custom Endpoints**: Extend Controller classes

## 📝 API Examples

### Creating a new entity:
\`\`\`bash
curl -X POST http://localhost:8080/api/entities \\
  -H "Content-Type: application/json" \\
  -d '{"name": "Example"}'
\`\`\`

### Getting all entities:
\`\`\`bash
curl http://localhost:8080/api/entities
\`\`\`

## 🏷️ Generated by UML Diagram Tool

This project structure and code were automatically generated from your UML class diagram design.

**Generation Details**:
- **Generated on**: ${new Date().toISOString().split('T')[0]}
- **Entities**: ${classEntities.length}
- **Relations**: ${this.diagram.relations.length}
- **Package**: \`${this.packageName}\`

---

For more information about the UML Diagram Tool, visit our documentation.
`,
    };
  }

  private toPascalCase(str: string): string {
    return str.replace(/[-_\s]+(.)?/g, (_, c) => (c ? c.toUpperCase() : '')).replace(/^(.)/, (_, c) => c.toUpperCase());
  }

  private toSnakeCase(str: string): string {
    return str
      .replace(/([A-Z])/g, '_$1')
      .toLowerCase()
      .replace(/^_/, '');
  }
}

export async function exportAsZip(diagram: UMLDiagram, projectName?: string, packageName?: string): Promise<void> {
  const exporter = new ProjectExporter(diagram, projectName, packageName);
  const files = exporter.exportCompleteProject();

  // Dynamic import of JSZip
  const JSZip = (await import('jszip')).default;
  const zip = new JSZip();

  files.forEach((file) => {
    zip.file(file.path, file.content);
  });

  const content = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(content);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${projectName || 'uml-generated-project'}.zip`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportDiagramAsJson(diagram: UMLDiagram): void {
  const dataStr = JSON.stringify(diagram, null, 2);
  const blob = new Blob([dataStr], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${diagram.name || 'uml-diagram'}.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}